name: 'Install Toolchain'
description: 'Install Toolchain required for a full build'
runs:
  using: "composite"
  steps:
    - name: Get last commit
      shell: bash
      id: last-toolchain
      run: |
        SHA=$(gh api repos/RMerl/am-toolchains/commits --jq '.[0].sha' | tr -d '\n')
        echo "::set-output name=last-commit::${SHA}"
    - name: Cache multiple paths
      uses: actions/cache@v2
      id: toolchains-cache
      with:
        path: am-toolchains
        key: ${{ runner.os }}-RMerl/am-toolchains-${{ steps.last-toolchain.outputs.last-commit }}
    - name: Check out repository code
      if: steps.toolchains-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: 'RMerl/am-toolchains'
        path: 'am-toolchains'
    - run: |
        mkdir -p ${{ github.workspace }}/hnd/tools/linux/
        ln -s ${{ github.workspace }}/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3 ${{ github.workspace }}/hnd/tools/linux/hndtools-arm-linux-2.6.36-uclibc-4.5.3 
        sudo ln -s ${{ github.workspace }}/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3 /opt/brcm-arm 
        sudo ln -s ${{ github.workspace }}/am-toolchains/brcm-arm-hnd /opt/toolchains
      shell: bash